name: Sanitize PR Comments

on:
  pull_request_review_comment:
    types: [created, edited]

jobs:
  sanitize:
    runs-on: ubuntu-latest
    permissions:
        pull-requests: write
        contents: write
        issues: write
        actions: write
    steps:
      - name: Run PR sanitizer action
        uses: ravikiran763/pr-sanitizer@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          openaiApiKey: ${{ secrets.OPENAI_API_KEY }}
          pr: ${{ github.event.pull_request.number }}
          repo: ${{ github.repository }}
